apiVersion: v1            # Core Kubernetes API version
kind: ConfigMap           # ConfigMap resource to hold configuration data
metadata:
  name: backend-config    # The name of this ConfigMap
data:
  HOST: "0.0.0.0"        # Default host IP bound by your Flask app
  PORT: "5000"           # Default port your Flask app listens on
  #APP_ENV: "production"   # Optional environment indicator for your app
  #LOG_LEVEL: "info"      # Optional log level setting
